name: pos_hybrid_app
description: "Manage Kaspi POS terminal"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  webview_flutter:
  intl: 
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
     - family: Nunito
       fonts:
         - asset: assets/fonts/Nunito-Regular.ttf